spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/search?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul
    username: root
    password: Admin123!

mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml